; ********************************************************************
; *** Source generated by  »» Level-Ed V2.4 ««  © 1991 by R.Werner ***
; ********************************************************************

	BITDEF	LEV,StandFlag,$0
	BITDEF	LEV,WandFlag,$1
	BITDEF	LEV,LeiterFlag,$2
	BITDEF	LEV,SturzFlag,$3
